### ISSUE TITLE
Debug GND pin

### ISSUE THREAD

**Issue by bjorn-felle** [thinghacker/Amiga600KeyboardUSBAdapter#2]
Thank you for this project :) I hope it's ok to post this question as an issue here. I'd like to build this using a Pi Pico breakout board so I can have the Pico socketed and use screw terminals to connect other components. None of the prefab breakout boards I have found have the debug pins connected. Is it essential to have the debug GND pin connected? I could solder on to this pin and then connect this on the breakout board to one of the GND screw terminals if necessary but I'd rather not modify the Pico unless it's absolutely necessary

**Comment by thinghacker** [comment]
Hi, the front side of the PCB has a filled zone of which the ground pins (including the debug ground) is attached, so there should be requirement *_NOT*_ to connect this in your case.

![image](https://user-images.githubusercontent.com/36720937/155974655-fd1f7498-897a-47ec-bbaf-240c9757d078.png)

**Comment by bjorn-felle** [comment]
Thank you, that makes sense. I'll solder a wire to that pin on the Pico and then connect it to one of the spare GND pins on the screw terminal board. Thank you again, I'm excited to make this part of my A600 case mod :)

**Comment by thinghacker** [comment]
@bjorn-felle - this is a bit embarrassing but I didn't include the NOT part in my response - you can leave the GND pin associated with debug free.  Sorry for the confusion, I hope this helps you with your mod.  The A600 seems to miss out on a lot of the love other Amigas tend to get!

**Comment by bjorn-felle** [comment]
That's ok, I appreciate the replies! Just to be sure we're not at crossed purposes, I'm not going to make the PCB but will be breadboarding the circuit. So in this case I just leave the debug GND pin hanging and not connected to anything is that right? Sorry if this is the wrong place to discuss this by the way.

**Comment by thinghacker** [comment]
Maybe you have already built it now but no, you do not need to connect the debug ground pin here
